/* UI-only enhancements. Does not replace existing game/auth logic. */
(function(){
  'use strict';
  const path=(location.pathname.split('/').pop()||'home.html').toLowerCase();
  const games=[['home.html','HOME'],['wingo_30s.html','30S'],['wingo_1m.html','WINGO'],['k3_1m.html','K3'],['trx_1m.html','TRX'],['ewingo_1m.html','ELITE W'],['etrx_1m.html','ELITE T']];
  function toast(msg){let t=document.querySelector('.v2-toast');if(!t){t=document.createElement('div');t.className='v2-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
  function addNav(){if(document.querySelector('.v2-nav')||path==='login.html')return;const nav=document.createElement('nav');nav.className='v2-nav';games.forEach(([url,label])=>{const a=document.createElement('a');a.href=url;a.textContent=label;if(path===url)a.classList.add('active');nav.appendChild(a)});const live=document.createElement('div');live.className='v2-live';live.innerHTML='<span class="v2-dot"></span> LIVE';nav.appendChild(live);const host=document.querySelector('.app-wrapper')||document.querySelector('.container')||document.body;host.parentNode.insertBefore(nav,host);}
  function addHelp(){if(path==='login.html'||document.querySelector('.v2-modal'))return;const m=document.createElement('div');m.className='v2-modal';m.innerHTML='<div class="v2-modal-card"><button class="v2-close">Close</button><h3>Quick controls</h3><p>Use the tabs for live history, prediction history and engine statistics. The existing data/logic layer remains connected; this panel only adds a cleaner control surface.</p></div>';document.body.appendChild(m);m.querySelector('.v2-close').onclick=()=>m.classList.remove('show');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});const b=document.createElement('button');b.textContent='HELP';b.onclick=()=>m.classList.add('show');document.querySelector('.v2-nav')?.appendChild(b)}
  function addCopy(){const period=document.querySelector('#upcomingIssue,#predPeriod');if(!period)return;const b=document.createElement('button');b.textContent='COPY';b.title='Copy current period';b.onclick=()=>{const text=(document.querySelector('#upcomingIssue')?.textContent||document.querySelector('#predPeriod')?.textContent||'').replace(/^Upcoming:\s*/i,'').trim();if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>toast('Period copied')).catch(()=>toast('Copy unavailable'));else toast(text)};document.querySelector('.v2-nav')?.appendChild(b)}
  function init(){document.body.classList.toggle('login-v2',path==='login.html');addNav();addHelp();addCopy();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
